### PR TITLE
one bug fix, some minor corrections

### PR DESCRIPTION
**Pull request by joevt**
I'm sorry I didn't get this done sooner. I was working on an EFI version of gfxutil to investigate how my MacMini8,1 does the NVMe node so that I can clean up the Patched SasEx workaround.

### CODE REVIEW

**Comment by joevt** [comment]
My EFI version of the gfxutil command still needs some work. I found some interesting stuff though. Here are the changes I need to do there:

1)
Add indenting to show device handle parent/child relationships. These are not the same as device path parent/child relationships - for example, some child device nodes are not child handles of the handle for the parent device node.

2)
There are devices on my MacMini8,1 with strange device path nodes that cause the EFI Shell commands "dh" and "devtree -d" to hang when trying to convert them to text. The devices that have the problem are "Generic Usb Keyboard" and "Generic Usb Mouse". The node that causes the problem is "030A050001" and "030A050002". The problem is Type 3:10 should include a 16 byte GUID but only includes a single byte (01 or 02). I have code to look for such problems, report them, and skip over paths that have nodes with invalid sizes so it won't hang.

3)
Right now, EFI gfxutil appears to be using code inside itself to convert paths to and from text. I think the EFI Shell does the same thing (at least the one compiled by Clover). I have an older EFI Shell that I used with rEFInd which appears to use code outside itself - at least, it outputs devices with nodes 'aNVMe' for the Apple NVMe device in my MacMini8,1. I need to figure out where that is coming from and make gfxutil use that code. I think I might need to load the 
"Device Path from Text Protocol" and "Device Path to Text Protocol". I want to figure out how to dump the rom of the MacMini8,1 and use UEFITool on that to find the Device Path to/from Text Protocol code or whatever code might be outputting "aNVMe".

4)
The functions currently used to convert to text don't seem to honour the DisplayOnly or AllowShortcuts flags. Or maybe I haven't found examples yet that will show a difference in the paths.

5)
The EFI Shell seems to support pipes. Add this feature to the EFI gfxutil like the normal gfxutil does. Add the other features of the normal gfxutil that may be useful while in the EFI Shell.

**Comment by vit9696** [comment]
Thanks for the patch!

I disagree with the removal of `-t` option and making it the default. Tools rely on `-p` working as is, and it is not possible to inject properties to any devices that PCI, thus `-t` view is not really useful for anybody but developers. Please revert this.

I disagree with the removal of newline for `gfxutil -d IODeviceTree:/chosen boot-device-path` when tty is present. Please check for tty presence and add a newline. In this case both piping and user visibility will be handled.

**Comment by vit9696** [comment]
As we plan a release on Monday, I am not positive this will make it in time for the release, but we can try.

**Comment by vit9696** [comment]
Thanks, merged!

**Pull request merged**
